SCHOOL_TYPES_DICT = [('CCI', 'CCI'),
                     ('CEI_CONVENIADO', 'CEI_CONVENIADO'),
                     ('CEI_MUNICIPAL', 'CEI_MUNICIPAL'),
                     ('CEI_PARCEIRO_(RP)', 'CEI_PARCEIRO_(RP)'),
                     ('CEMEI', 'CEMEI'),
                     ('CEU_GESTÃO', 'CEU_GESTÃO'),
                     ('CIEJA', 'CIEJA'),
                     ('EMEBS', 'EMEBS'),
                     ('EMEF', 'EMEF'),
                     ('EMEFM', 'EMEFM'),
                     ('EMEI', 'EMEI'),
                     ('PROJETO_CECI', 'PROJETO_CECI'),
                     ('SME_CONVÊNIO', 'SME_CONVÊNIO')]

GROUPING_DICT = [('1', '1'),
                 ('2', '2'),
                 ('3', '3'),
                 ('4', '4'),
                 ('EDITAL 78/2016', 'EDITAL 78/2016')]
EDITOR_DICT = [('Nenhum', 'Nenhum'),
               ('EDITAL 78/2016', 'EDITAL 78/2016')]
MEALS_DICT = [('A - ALMOCO', 'A - ALMOCO'),
              ('AA - ALMOCO ADULTO', 'AA - ALMOCO ADULTO'),
              ('C - COLACAO', 'C - COLACAO'),
              ('D - DESJEJUM', 'D - DESJEJUM'),
              ('FPJ - FILHOS PRO JOVEM', 'FPJ - FILHOS PRO JOVEM'),
              ('J - JANTAR', 'J - JANTAR'),
              ('L - LANCHE', 'L - LANCHE'),
              ('L4 - LANCHE 4 HORAS', 'L4 - LANCHE 4 HORAS'),
              ('L5 - LANCHE 5 HORAS', 'L5 - LANCHE 5 HORAS'),
              ('L5 - LANCHE 5 OU 6 HORAS', 'L5 - LANCHE 5 OU 6 HORAS'),
              ('MI - MERENDA INICIAL', 'MI - MERENDA INICIAL'),
              ('MES - MERENDA ESPEC_SECA', 'MES - MERENDA ESPEC_SECA'),
              ('MS - MERENDA SECA', 'MS - MERENDA SECA'),
              ('SR - SEM REFEICAO', 'SR - SEM REFEICAO'),
              ('R1 - REFEICAO 1', 'R1 - REFEICAO 1')]
AGES_DICT = [('A - 0 A 1 MES', 'A - 0 A 1 MES'),
             ('B - 1 A 3 MESES', 'B - 1 A 3 MESES'),
             ('C - 4 A 5 MESES', 'C - 4 A 5 MESES'),
             ('D - 0 A 5 MESES', 'D - 0 A 5 MESES'),
             ('D - 6 A 7 MESES', 'D - 6 A 7 MESES'),
             ('D - 6 MESES', 'D - 6 MESES'),
             ('D - 7 MESES', 'D - 7 MESES'),
             ('E - 8 A 11 MESES', 'E - 8 A 11 MESES'),
             ('X - 1A -1A E 11MES', 'X - 1A -1A E 11MES'),
             ('F - 2 A 3 ANOS', 'F - 2 A 3 ANOS'),
             ('G - 4 A 6 ANOS', 'G - 4 A 6 ANOS'),
             ('I - 2 A 6 ANOS', 'I - 2 A 6 ANOS'),
             ('W - EMEI DA CEMEI', 'W - EMEI DA CEMEI'),
             ('N - 6 A 7 MESES PARCIAL', 'N - 6 A 7 MESES PARCIAL'),
             ('O - 8 A 11 MESES PARCIAL', 'O - 8 A 11 MESES PARCIAL'),
             ('Y - 1A -1A E 11MES PARCIAL', 'Y - 1A -1A E 11MES PARCIAL'),
             ('P - 2 A 3 ANOS PARCIAL', 'P - 2 A 3 ANOS PARCIAL'),
             ('Q - 4 A 6 ANOS PARCIAL', 'Q - 4 A 6 ANOS PARCIAL'),
             ('H - ADULTO', 'H - ADULTO'),
             ('Z - UNIDADES SEM FAIXA', 'Z - UNIDADES SEM FAIXA'),
             ('S - FILHOS PRO JOVEM', 'S - FILHOS PRO JOVEM'),
             ('V - PROFESSOR', 'V - PROFESSOR'),
             ('U - PROFESSOR JANTAR CEI', 'U - PROFESSOR JANTAR CEI')]
MANAGEMENT_DICT = [('DIRETA', 'DIRETA'),
                   ('MISTA', 'MISTA'),
                   ('TERCEIRIZADA', 'TERCEIRIZADA')]
